function GsRSkPlot = plotSatGs_RSk()
%%%%%Subplot function for supplementary figure A5_d%%%%%
%Plot of predicted satellite copulation rewards given the fitness loss
%scenario where most copulations are drawn away from low
%ranking residents by a co-display. 
 
h="RSk";
%matrix for predicted values from function
Mat_G_Sat_s=zeros(7,7);
%Satellite competitive ability
Sat_Com_ab="medium";
Comp_level="medium";
%Satellite copulation gains by lek size
Mat_G_Sat_s(1:7,1)=[Satellite_rewards(1,1,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan,nan,nan];
%L=2
Mat_G_Sat_s(1:7,2)=[Satellite_rewards(2,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(2,2,h,Sat_Com_ab,Comp_level),nan,nan,nan,nan,nan];
%L=3
Mat_G_Sat_s(1:7,3)=[Satellite_rewards(3,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(3,2,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(3,3,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan];
%L=4
Mat_G_Sat_s(1:7,4)=[Satellite_rewards(4,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(4,2,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(4,3,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(4,4,h,Sat_Com_ab,Comp_level),nan,nan,nan];
%L=5
Mat_G_Sat_s(1:7,5)=[Satellite_rewards(5,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(5,2,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(5,3,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(5,4,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(5,5,h,Sat_Com_ab,Comp_level),nan,nan];
%L=6
Mat_G_Sat_s(1:7,6)=[Satellite_rewards(6,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(6,2,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(6,3,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(6,4,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(6,5,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(6,6,h,Sat_Com_ab,Comp_level),nan];
%L=7
Mat_G_Sat_s(1:7,7)=[Satellite_rewards(7,1,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,2,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,3,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,4,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,5,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,6,h,Sat_Com_ab,Comp_level),...
    Satellite_rewards(7,7,h,Sat_Com_ab,Comp_level)];



  
 
Title_plot="(d)"; 
sub_plot_num=4;
subplot_position=[0.399 0.15 0.3347 0.3412];
Mat_G_Sat_r = get_all_G_Sat_r( h,Sat_Com_ab,Comp_level);
response_colormap=colormap_Sat_rewards( );
color_axis_limits=[0 4];
C_ticks=[0 1 2 3 4];
c_ram_dec=[];
C_ramp_position=[0 0 0 0];
C_axis_lab=[];
%%%plot
GsRSkPlot = ...
    plot_response_rank_and_lek_size_four_subplot...
    (Title_plot, sub_plot_num,subplot_position,Mat_G_Sat_s,...
    response_colormap,color_axis_limits,C_ramp_position,C_ticks,...
    c_ram_dec,C_axis_lab);

%%%%add anotations
       text(0.8,max_resident_per_lek( 1, Mat_G_Sat_r)+0.1,2,{'*'},...
           'Color',[0.75 0.75 0.75],'FontWeight',...
           'bold','FontSize',28)
       text(1.8,max_resident_per_lek( 2, Mat_G_Sat_r)+0.1,1.1,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)
       text(2.8,max_resident_per_lek( 3, Mat_G_Sat_r)+0.1,1.1,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)
       text(3.8,max_resident_per_lek( 4, Mat_G_Sat_r)+0.1,1.1,{'*'},...
           'Color',white_or_black_asterisk( 4,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)
       text(4.8,max_resident_per_lek( 5, Mat_G_Sat_r)+0.1,1.1,{'*'},...
           'Color',white_or_black_asterisk( 5,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)
       text(5.8,max_resident_per_lek( 6, Mat_G_Sat_r)+0.1,1.1,{'*'},...
           'Color',white_or_black_asterisk( 6,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)
       text(6.8,max_resident_per_lek( 7, Mat_G_Sat_r)+0.1,2,{'*'},...
           'Color',white_or_black_asterisk( 7,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',28)

end
   







