function GsskPlot  = PlotGs_sens_lek_comp(Comp_level)
%%%%%Subplot function for supplementary figure A11_weak-strong%%%%%
%Plot of predicted satellite copulation rewards given the fitness loss
%scenario where the most copulations are drawn away from high 
%ranking residents by a co-display under different satellite competitive 
%abilities: weak, medium, and strong. 
 
h="Sk";
%matrix for predicted values from function
%Satellite competitive ability
Sat_Com_ab="medium";
%inputs for plot
Mat_G_Sat_r = get_all_G_Sat_r( h,Sat_Com_ab,Comp_level);
Gs_colormap = colormap_Sat_rewards( );
color_axis_limits=[0.0 4.0];

  
 


%Make a figure
switch Comp_level
    case "high"
        Title_plot="(b)";
        sub_plot_num=2; 
        X_label="";
        Y_label="";
        GsskPlot = ...
        plot_response_rank_and_lek_size_12_subplot...
        (Title_plot, sub_plot_num,Mat_G_Sat_r,Gs_colormap,...
        color_axis_limits,X_label,Y_label);
    %%%%add anotations
       text(0.8,max_resident_per_lek( 1, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 1,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(1.8,max_resident_per_lek( 2, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(2.8,max_resident_per_lek( 3, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(3.8,max_resident_per_lek( 4, Mat_G_Sat_r)+0.1,6,{'*'},...
           'Color',white_or_black_asterisk( 4,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(4.8,max_resident_per_lek( 5, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 5,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(5.8,max_resident_per_lek( 6, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 6,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(6.8,max_resident_per_lek( 7, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 7,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)

     case "medium"
        Title_plot="";
        sub_plot_num=6; 
        X_label="";
        Y_label="";
        GsskPlot = ...
        plot_response_rank_and_lek_size_12_subplot...
        (Title_plot, sub_plot_num,Mat_G_Sat_r,Gs_colormap,...
        color_axis_limits,X_label,Y_label);
    %%%%add anotations
       text(0.8,max_resident_per_lek( 1, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 1,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(1.8,max_resident_per_lek( 2, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(2.8,max_resident_per_lek( 3, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(3.8,max_resident_per_lek( 4, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 4,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(4.8,max_resident_per_lek( 5, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 5,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(5.8,max_resident_per_lek( 6, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 6,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(6.8,max_resident_per_lek( 7, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 7,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
      case "low"
       Title_plot="";
        sub_plot_num=10; 
        X_label="Residents/lek";
        Y_label="";
        GsskPlot = ...
        plot_response_rank_and_lek_size_12_subplot...
        (Title_plot, sub_plot_num,Mat_G_Sat_r,Gs_colormap,...
        color_axis_limits,X_label,Y_label);
    %%%%add anotations
       text(0.8,max_resident_per_lek( 1, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 1,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(1.8,max_resident_per_lek( 2, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(2.8,max_resident_per_lek( 3, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 2,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(3.8,max_resident_per_lek( 4, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 4,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(4.8,max_resident_per_lek( 5, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 5,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(5.8,max_resident_per_lek( 6, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 6,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
       text(6.8,max_resident_per_lek( 7, Mat_G_Sat_r)+0.1,4,{'*'},...
           'Color',white_or_black_asterisk( 7,Mat_G_Sat_r),'FontWeight',...
           'bold','FontSize',22)
                C_Bticks=[0.00 1.00 2.0 3.00 4.00];
                hr1 = colorbar('Ticks',[],'Position',...
                    [0.48 0.11 0.02 0.817],...
                    'YAxisLocation','right','XTick', C_Bticks);
                    hr1.Limits = [0.0 4.0];
                    text(9,0.5,0,...
                        {'Satellite co-display copulation reward'},...
                        'Color','black','FontSize',18,'Rotation',90)
                    set(hr1,'TickDir','out','xticklabel',...
                        num2str(get(hr1,'xtick')','%.1f'))


end



