function MatSatPr = get_all_Sat_prop_co_dis( h,Sat_Com_ab,Comp_level)
%creates matrix with all predicted proportion of copulations a satellite 
%recieves with in a co-display given the fitness loss scenario, 
%competition between reisdents, and the satellites competitive ability
%matrix for predicted values from function
MatSatPr=zeros(7,7);
%Satellite proportion by lek size
%L=1
MatSatPr(1:7,1)=[Satellite_proportion(1,1,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan,nan,nan];
%L=2
MatSatPr(1:7,2)=[Satellite_proportion(2,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(2,2,h,Sat_Com_ab,Comp_level),nan,nan,nan,nan,nan];
%L=3
MatSatPr(1:7,3)=[Satellite_proportion(3,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(3,2,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(3,3,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan];
%L=4
MatSatPr(1:7,4)=[Satellite_proportion(4,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(4,2,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(4,3,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(4,4,h,Sat_Com_ab,Comp_level),nan,nan,nan];
%L=5
MatSatPr(1:7,5)=[Satellite_proportion(5,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(5,2,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(5,3,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(5,4,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(5,5,h,Sat_Com_ab,Comp_level),nan,nan];
%L=6
MatSatPr(1:7,6)=[Satellite_proportion(6,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(6,2,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(6,3,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(6,4,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(6,5,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(6,6,h,Sat_Com_ab,Comp_level),nan];
%L=7
MatSatPr(1:7,7)=[Satellite_proportion(7,1,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,2,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,3,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,4,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,5,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,6,h,Sat_Com_ab,Comp_level),...
    Satellite_proportion(7,7,h,Sat_Com_ab,Comp_level)];



end

