function PercSatCopPlot = plotPercSatCop_RSk()
%%%%%Subplot function for supplementary figure A7_d%%%%%
%Plot of predicted satellite percent copulations given the fitness loss
%scenario where copulations are drawn by a co-display in the highest 
%proportion from low ranking residents. 
 
h="RSk";
%matrix for predicted values from function
MatPercCopSat=zeros(7,7);
%Satellite competitive ability
Sat_Com_ab="medium";
Comp_level="medium";
%Satellite copulation percentage
%L=1
MatPercCopSat(1:7,1)=[CopSatPerc(1,1,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan,nan,nan];
%L=2
MatPercCopSat(1:7,2)=[CopSatPerc(2,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(2,2,h,Sat_Com_ab,Comp_level),nan,nan,nan,nan,nan];
%L=3
MatPercCopSat(1:7,3)=[CopSatPerc(3,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(3,2,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(3,3,h,Sat_Com_ab,Comp_level),...
    nan,nan,nan,nan];
%L=4
MatPercCopSat(1:7,4)=[CopSatPerc(4,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(4,2,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(4,3,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(4,4,h,Sat_Com_ab,Comp_level),nan,nan,nan];
%L=5
MatPercCopSat(1:7,5)=[CopSatPerc(5,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(5,2,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(5,3,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(5,4,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(5,5,h,Sat_Com_ab,Comp_level),nan,nan];
%L=6
MatPercCopSat(1:7,6)=[CopSatPerc(6,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(6,2,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(6,3,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(6,4,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(6,5,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(6,6,h,Sat_Com_ab,Comp_level),nan];
%L=7
MatPercCopSat(1:7,7)=[CopSatPerc(7,1,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,2,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,3,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,4,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,5,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,6,h,Sat_Com_ab,Comp_level),...
    CopSatPerc(7,7,h,Sat_Com_ab,Comp_level)];




  
 
Title_plot="(d)"; 
sub_plot_num=4;
subplot_position=[0.399 0.15 0.3347 0.3412];
response_colormap=colormap_sat_percent( );
color_axis_limits=[0 20];
C_ticks=[];
c_ram_dec=[];
C_ramp_position=[0 0 0 0];
C_axis_lab=[];

%%%plot
PercSatCopPlot = ...
    plot_response_rank_and_lek_size_four_subplot...
    (Title_plot, sub_plot_num,subplot_position,MatPercCopSat,...
    response_colormap,color_axis_limits,C_ramp_position,C_ticks,...
    c_ram_dec,C_axis_lab);



end



